source "https://rubygems.org"
ruby '2.5.1'
gem 'rspec'
gem 'pry'
gem 'rubocop', '~> 0.57.2'
gem 'nokogiri'
gem 'watir'
gem 'webdrivers'
gem 'faker'
gem 'launchy'
gem 'selenium-webdriver'
gem 'json'
gem 'google_drive'
gem 'csv'
#gem 'pp'